### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by Elijha** [iantearle/iSkip#1]
Some more information is needed on how the image array is assigned .  It's not even close to clear how this is called and only from digging around the authors site on his implementation was I able to find his call using an assigned array for the images - is this how it is meant to be / the only way?

``` var array = [
          '/expanse/themes/html5/images/iantearle_logo.png',
          '/expanse/themes/html5/images/iskip/iskip_heritage_app.png',
          '/expanse/themes/html5/images/iskip/iskip_beer_tap.png',
        ]
        $(".iskip").iskip({images:array, method:'mousemove', 'cycle':1});

```

The readme doesn't talk about the images array at all, so I was lsot wondering how it is assigned.
- ideally and example HTML.
- Must all image be the same size / type.

Should it be;
```

< div id="iskip">
   < img src="1.gif">< img src="1.gif">< img src="1.gif">
< /div>

```
or
```

< ul id="iskip">
 <  li><img src="1.gif"></li>
 < li><img src="1.gif"></li>
 < li><img src="1.gif"></li>
< /ul>

```
```

**Comment by iantearle** [comment]
You only need to supply an array of images. 

This can be an in line array i.e. var array = ['image.extension','image.extension']; or an array in a separate file. 

No need to add you markup for additional images in your class, as your key image will be singular inline in your code, better for fall back; you style one image on the page and iSkip will allow for the functionality of skimming over photos on your key image.

iSkip only supplies the raw image src as is; `<img />` no wrapping of `<li />` or `<div />`. 

Then you just need a class or id to call upon. Add this to your key image, and iSkip will change the src as you move your mouse over it. 

Effectively your markup would look like:

`<script>
var array = [
'2.gif',
'3.gif,
'4.gif
]
$(".iskip").iskip({images:array, method:'mousemove', 'cycle':1});
</script>
<div>
<img src="1.gif" alt="" class="iskip" />
</div>`

**Comment by iantearle** [comment]
I should add that iSkip will add an image tag with a style of display: none at the bottom of the page, this allows for seamless skimming over the skip element as all the images are loaded upon opening the webpage. `<img src="http://farm7.static.flickr.com/6152/6175782097_97c514039c.jpg" style="display: none; ">`

**Comment by Elijha** [comment]
Thanks for your quick response. This is an excellent plugin and I like it very much.

It should also be noted that all images should have the same dimensions, or failing that the image tag should have a with and height values set or failing that set them in css. Other wise the images when replace will change size and this can effect your layout.
